name: JavaScript CICD

on:
  push:
    branches:
      - cicd-pr
  pull_request:
    branches:
      - cicd-pr

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./JavaScript/starter
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
